version: "2"



services:

  ocr:
    #image: clearlinux/tesseract-ocr
    image: test
    ports: 
      - "1125:25"
    volumes: 
      - ./smtp:/app
    #command: tesseract /app/newimage.tif /app/out -l deu+eng --psm 3 --oem 1 pdf
    command: npm run debug
    env_file: .env
    environment: 
      - SMTP_IN_USER=printer         # default: ""
      - SMTP_IN_PASS=printer         # default: ""
      - SMTP_IN_PORT=25              # default: 25
      - SMTP_OUT_HOST=192.168.81.1   # default: localhost
      - SMTP_OUT_PORT=1025           # default: 25
      #- SMTP_OUT_USER=              # default: "" #set in .env
      #- SMTP_OUT_PASS=              # default: "" #set in .env
      #- SMTP_OUT_FROM=              # default: keep original address

# convert -density 288 Scan29-12-2020-145431.pdf output.tif