version: "2.2"

# docker-compose -f docker-compose-debug.yml run --rm ocr bash

services:

  ocr:
    image: ghcr.io/werty1st/smtp-tesseract-ocr:latest
    build: 
      dockerfile: Dockerfile
      context: .
    ports: 
      - "1126:25"
    volumes: 
      - ./smtp:/app
    #command: npm run debug
    command: npm run serve
    env_file: .env
    environment: 
      - SMTP_IN_USER=printer         # default: ""
      - SMTP_IN_PASS=printer         # default: ""
      - SMTP_IN_PORT=25              # default: 25
      - SMTP_OUT_HOST=192.168.81.1   # default: localhost
      - SMTP_OUT_PORT=1025           # default: 25
      #- SMTP_OUT_USER=              # default: "" #set in .env
      #- SMTP_OUT_PASS=              # default: "" #set in .env
      #- SMTP_OUT_FROM=              # default: keep original address
